Configurable Delegation Limits
casper-network/ceps pull request #90
Opened 2024-02-20 10:07 UTC by wojcik91

2025-04-22 22:47 UTC, mssteuer approved these changes

2025-04-24 04:43 UTC, devendran-m commented
Hi @mrkara ,
Could you approve this PR please?

2025-04-24 10:15 UTC, mrkara requested changes
Looks good to me apart from a small typo.

2025-04-28 23:06 UTC, mrkara approved these changes

2025-04-28 23:07 UTC, merged